name: release-to-maven-central
on:
  workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Releasing to Maven Central"

      - uses: actions/checkout@v2

      - name: Set up settings.xml for Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Remove SNAPSHOT from versions
        run: mvn versions:set -DremoveSnapshot=true versions:commit --no-transfer-progress

      - name: "Build Changelog"
        id: changelog
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "::set-output name=VERSION::$VERSION"

      - name: Commit release version
        uses: EndBug/add-and-commit@v7
        with:
          message: Releasing v${{ steps.get_version.outputs.VERSION }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          release_name: v${{ steps.get_version.outputs.VERSION }}
          body: |
            Released new version.  Some notes here.

            ### Things that changed in this release
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
